### PR TITLE
Clarify language about aggregate 401k contributions

### PR DESCRIPTION
**Pull request by waldoj**
The existing text was ungrammatical and confusing.

### CODE REVIEW

**Comment by waldoj** [comment]
I...have no idea what's happening.

**Comment by waldoj** [comment]
How the hell did forking 18F's repo fork _your_ copy?

**Comment by krues8dr** [comment]
:flailing-octopus:

**Comment by krues8dr** [comment]
Check your remotes!

**Comment by waldoj** [comment]
:two-flailing-octopuses:

**Pull request closed without merging**
